### ISSUE TITLE
Bootstrap icons don't work

### ISSUE THREAD

**Issue by danclarke** [w3tecch/aurelia-typescript-boilerplate#4]
If you add a Bootstrap icon to a template, it'll appear as a square.

For example:

`<p><span class="glyphicon glyphicon-search" aria-hidden="true"></span></p>`

Results in a square on the page instead of the magnifying glass.

**Comment by dweber019** [comment]
I'll check into that but I'm actually using font awesome.

**Comment by danclarke** [comment]
Thanks. A workaround I have for now is to ensure the glyphicons fonts are copied to 'fonts/bootstrap' and added the following to the top of _variables.scss:

```
$icon-font-path: '/fonts/bootstrap/';

@function font-path($path) {
  @return $path;
}
```

**Comment by dweber019** [comment]
Thanks for the hint
