### ISSUE TITLE
Copying of assets

### ISSUE THREAD

**Issue by danclarke** [w3tecch/aurelia-typescript-boilerplate#5]
Images in SASS are automatically brought across to dist, but content referenced in the Aurelia templates isn't. This might be something I'm missing. For now, I've worked around by including '@easy-webpack/config-copy-files', and using the config below:

```
  const copyConfig = {
    patterns: [
      { from: 'node_modules/bootstrap-sass/assets/fonts/bootstrap', to: 'fonts/bootstrap' },
      { from: 'src/robots.txt' },
      { from: 'src/assets', to: 'src/assets' }
    ],
    options: {
        copyUnmodified: true,
        debug: 'info'
    }
  };
```

`require('@easy-webpack/config-copy-files')(copyConfig),`

**Comment by dweber019** [comment]
There was a major release. Please check again. Thx
